services:
  dashboard:
    build:
      context: .
    container_name: 'teddie-dash'
    env_file: .env
    environment:
      NODE_ENV: production
    ports:
      - 127.0.0.1:5179:3000
    restart: unless-stopped
